### ISSUE TITLE
simplecpp fails to expand concatenated macro

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#32] opened 2016-08-09 22:33 UTC
Code example:

```
#define REP1(value)		value
#define REP2(value)		REP1(value), value
#define REP3(value)		REP2(value), value
#define REP4(value)		REP3(value), value
#define REP5(value)		REP4(value), value
#define REP6(value)		REP5(value), value
#define REP7(value)		REP6(value), value
#define REP8(value)		REP7(value), value
#define REP9(value)		REP8(value), vale

#define ARRAY(value, n)	REP##n(value)

ARRAY(1, 5)
```

simplecpp output is wrong:

```
> cppcheck --version
Cppcheck 1.75
> cppcheck -q -E main.c 

 REP5  ( 1  )
```

**Comment by danmar** [comment] 2016-08-10 19:33
This might be a duplicate of #22

**Closed** 2016-08-28 06:31 UTC
