### ISSUE TITLE
simplecpp fails to include file when name is defined by a macro

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#34] opened 2016-08-10 08:46 UTC
include.h:

```
int i;
```

main.c:

```
#define INCLUDE_FILE "include.h"
#include INCLUDE_FILE
```

```
> cppcheck --version
Cppcheck 1.75
> cppcheck -q -E main.c

>
```

**Comment by danmar** [comment] 2016-08-10 18:58
This is a duplicate of #3

**Comment by mavik1** [comment] 2016-10-25 20:37
This issue is present in cppcheck 1.76.1. Is it possible to reopen the ticket?

**Comment by danmar** [comment] 2016-10-29 18:21
I can confirm that it does not work with simplecpp HEAD

    daniel@debian:~/simplecpp$ ./simplecpp 34.c 
    
    34.c:2: missing header: Header not found: INCLUDE_FILE

**Closed** 2016-11-08 21:34 UTC
