### ISSUE TITLE
Commented out cppcheck suppression is not ignored

### ISSUE THREAD

**Issue by mavik1** [danmar/simplecpp#203] opened 2021-01-10 13:50 UTC
I'm not sure if this is a cppcheck issue or a simplecpp issue. I wouldn't expect any unmatched suppression warnings from the following code:

```
#include "stdio.h"

int main(int argc, char *argv[])
{
#if 0
	// cppcheck-suppress directDynamicMemoryUsage
	printf("Hello world!\n");
#endif
}
```

```
> cppcheck --version
Cppcheck 2.3
> cppcheck main.c --enable=all --inline-suppr --suppress=missingInclude
Checking main.c ...
main.c:7:0: information: Unmatched suppression: directDynamicMemoryUsage [unmatchedSuppression]
 printf("Hello world!\n");
^
```

**Comment by danmar** [comment] 2021-01-10 15:56
More or less a duplicate of https://trac.cppcheck.net/ticket/5704

**Closed by danmar** 2021-01-10 15:56 UTC

**Comment by jpyllman** [comment] 2022-02-17 09:51
The problem with the code today is that we do not distinguish between error not suppressed and source code not checked. So when an error happen and there is no suppression we get an error message on screen. If there is an error and there is a suppression it is not displayed, and the suppression is marked as matched. But if no error happens the suppression is not marked as matched, or if the code is never checked because of #ifdef, then we display at the end that this suppression is not matched.

So if you do not specify any  -D or -U on the command line the parser tries all combinations of #ifdef to check all code. Also doing #ifdef 0 gives the same result.

So somehow we should add something that marks the suppression as checked. The problem is that it is only checked if there is an error in the code. So somehow need to trigger check, even if not error, but have suppression. And then the reportUnmatchedSuppressions() should only report checked suppressions that are unmatched.

I am writing some code.
